[deploy]
region = 'us-west-2'
certificateArnSSM = '/AlwaysOnward/certificateArn'
hostedZoneIdSSM = '/AlwaysOnward/hostedZoneId'
siteName = 'blog.always-onward.com'
zoneName = 'always-onward.com'
createNew = false

[email]
noReplyEmailSSM = ''
emailDynamoSSM = ''
