'use strict';

module.exports = Object.freeze({
  lookupPoint:  {
    "properties": {
      "@id": "https://api.weather.gov/points/47.6062,-122.3321",
      "@type": "wx:Point",
      "cwa": "SEW",
      "forecastOffice": "https://api.weather.gov/offices/SEW",
      "gridId": "SEW",
      "gridX": 124,
      "gridY": 67,
      "forecast": "https://api.weather.gov/gridpoints/SEW/124,67/forecast",
      "forecastHourly": "https://api.weather.gov/gridpoints/SEW/124,67/forecast/hourly",
      "forecastGridData": "https://api.weather.gov/gridpoints/SEW/124,67",
      "observationStations": "https://api.weather.gov/gridpoints/SEW/124,67/stations",
      "forecastZone": "https://api.weather.gov/zones/forecast/WAZ558",
      "county": "https://api.weather.gov/zones/county/WAC033",
      "fireWeatherZone": "https://api.weather.gov/zones/fire/WAZ654",
      "timeZone": "America/Los_Angeles",
      "radarStation": "KATX"
    }
  },
  getForecast: {
    "properties": {
      "updated": "2022-01-29T11:05:33+00:00",
      "units": "us",
      "forecastGenerator": "BaselineForecastGenerator",
      "generatedAt": "2022-01-29T15:14:02+00:00",
      "updateTime": "2022-01-29T11:05:33+00:00",
      "validTimes": "2022-01-29T05:00:00+00:00/P7DT20H",
      "elevation": {
        "unitCode": "wmoUnit:m",
        "value": 73.152000000000001
      },
      "periods": [
        {
          "number": 1,
          "name": "Today",
          "startTime": "2022-01-29T07:00:00-08:00",
          "endTime": "2022-01-29T18:00:00-08:00",
          "isDaytime": true,
          "temperature": 48,
          "temperatureUnit": "F",
          "temperatureTrend": "falling",
          "windSpeed": "7 mph",
          "windDirection": "SSE",
          "icon": "https://api.weather.gov/icons/land/day/bkn?size=medium",
          "shortForecast": "Mostly Cloudy",
          "detailedForecast": "Mostly cloudy. High near 48, with temperatures falling to around 45 in the afternoon. South southeast wind around 7 mph. New rainfall amounts less than a tenth of an inch possible."
        },
        {
          "number": 2,
          "name": "Tonight",
          "startTime": "2022-01-29T18:00:00-08:00",
          "endTime": "2022-01-30T06:00:00-08:00",
          "isDaytime": false,
          "temperature": 43,
          "temperatureUnit": "F",
          "temperatureTrend": null,
          "windSpeed": "6 to 9 mph",
          "windDirection": "S",
          "icon": "https://api.weather.gov/icons/land/night/rain,50/rain,90?size=medium",
          "shortForecast": "Light Rain",
          "detailedForecast": "Rain after 7pm. Cloudy, with a low around 43. South wind 6 to 9 mph. Chance of precipitation is 90%. New rainfall amounts between a tenth and quarter of an inch possible."
        },
        {
          "number": 3,
          "name": "Sunday",
          "startTime": "2022-01-30T06:00:00-08:00",
          "endTime": "2022-01-30T18:00:00-08:00",
          "isDaytime": true,
          "temperature": 47,
          "temperatureUnit": "F",
          "temperatureTrend": null,
          "windSpeed": "8 to 17 mph",
          "windDirection": "S",
          "icon": "https://api.weather.gov/icons/land/day/rain,90?size=medium",
          "shortForecast": "Light Rain",
          "detailedForecast": "Rain. Cloudy, with a high near 47. South wind 8 to 17 mph, with gusts as high as 23 mph. Chance of precipitation is 90%. New rainfall amounts between a tenth and quarter of an inch possible."
        },
        {
          "number": 4,
          "name": "Sunday Night",
          "startTime": "2022-01-30T18:00:00-08:00",
          "endTime": "2022-01-31T06:00:00-08:00",
          "isDaytime": false,
          "temperature": 37,
          "temperatureUnit": "F",
          "temperatureTrend": null,
          "windSpeed": "5 to 17 mph",
          "windDirection": "ESE",
          "icon": "https://api.weather.gov/icons/land/night/rain,70/rain,40?size=medium",
          "shortForecast": "Light Rain Likely",
          "detailedForecast": "Rain likely. Mostly cloudy, with a low around 37. East southeast wind 5 to 17 mph, with gusts as high as 23 mph. Chance of precipitation is 70%. New rainfall amounts between a tenth and quarter of an inch possible."
        },
        {
          "number": 5,
          "name": "Monday",
          "startTime": "2022-01-31T06:00:00-08:00",
          "endTime": "2022-01-31T18:00:00-08:00",
          "isDaytime": true,
          "temperature": 44,
          "temperatureUnit": "F",
          "temperatureTrend": null,
          "windSpeed": "2 to 8 mph",
          "windDirection": "S",
          "icon": "https://api.weather.gov/icons/land/day/rain,50?size=medium",
          "shortForecast": "Chance Light Rain",
          "detailedForecast": "A chance of rain. Partly sunny, with a high near 44. South wind 2 to 8 mph. Chance of precipitation is 50%. New rainfall amounts less than a tenth of an inch possible."
        },
        {
          "number": 6,
          "name": "Monday Night",
          "startTime": "2022-01-31T18:00:00-08:00",
          "endTime": "2022-02-01T06:00:00-08:00",
          "isDaytime": false,
          "temperature": 37,
          "temperatureUnit": "F",
          "temperatureTrend": null,
          "windSpeed": "3 mph",
          "windDirection": "S",
          "icon": "https://api.weather.gov/icons/land/night/rain,30?size=medium",
          "shortForecast": "Chance Light Rain",
          "detailedForecast": "A chance of rain. Mostly cloudy, with a low around 37. Chance of precipitation is 30%. New rainfall amounts less than a tenth of an inch possible."
        },
        {
          "number": 7,
          "name": "Tuesday",
          "startTime": "2022-02-01T06:00:00-08:00",
          "endTime": "2022-02-01T18:00:00-08:00",
          "isDaytime": true,
          "temperature": 42,
          "temperatureUnit": "F",
          "temperatureTrend": null,
          "windSpeed": "3 to 8 mph",
          "windDirection": "NW",
          "icon": "https://api.weather.gov/icons/land/day/rain,30/rain,20?size=medium",
          "shortForecast": "Chance Light Rain",
          "detailedForecast": "A chance of rain before 4pm. Mostly cloudy, with a high near 42. Chance of precipitation is 30%."
        },
        {
          "number": 8,
          "name": "Tuesday Night",
          "startTime": "2022-02-01T18:00:00-08:00",
          "endTime": "2022-02-02T06:00:00-08:00",
          "isDaytime": false,
          "temperature": 33,
          "temperatureUnit": "F",
          "temperatureTrend": null,
          "windSpeed": "2 to 8 mph",
          "windDirection": "ENE",
          "icon": "https://api.weather.gov/icons/land/night/bkn/snow?size=medium",
          "shortForecast": "Mostly Cloudy then Chance Light Snow",
          "detailedForecast": "A chance of snow after 4am. Mostly cloudy, with a low around 33."
        },
        {
          "number": 9,
          "name": "Wednesday",
          "startTime": "2022-02-02T06:00:00-08:00",
          "endTime": "2022-02-02T18:00:00-08:00",
          "isDaytime": true,
          "temperature": 41,
          "temperatureUnit": "F",
          "temperatureTrend": null,
          "windSpeed": "5 mph",
          "windDirection": "SSE",
          "icon": "https://api.weather.gov/icons/land/day/snow?size=medium",
          "shortForecast": "Chance Light Snow",
          "detailedForecast": "A chance of snow before 1pm, then a chance of rain. Mostly cloudy, with a high near 41."
        },
        {
          "number": 10,
          "name": "Wednesday Night",
          "startTime": "2022-02-02T18:00:00-08:00",
          "endTime": "2022-02-03T06:00:00-08:00",
          "isDaytime": false,
          "temperature": 35,
          "temperatureUnit": "F",
          "temperatureTrend": null,
          "windSpeed": "3 mph",
          "windDirection": "S",
          "icon": "https://api.weather.gov/icons/land/night/snow?size=medium",
          "shortForecast": "Chance Rain And Snow",
          "detailedForecast": "A chance of rain before 7pm, then a chance of rain and snow. Mostly cloudy, with a low around 35."
        },
        {
          "number": 11,
          "name": "Thursday",
          "startTime": "2022-02-03T06:00:00-08:00",
          "endTime": "2022-02-03T18:00:00-08:00",
          "isDaytime": true,
          "temperature": 44,
          "temperatureUnit": "F",
          "temperatureTrend": null,
          "windSpeed": "5 mph",
          "windDirection": "S",
          "icon": "https://api.weather.gov/icons/land/day/snow?size=medium",
          "shortForecast": "Slight Chance Rain And Snow",
          "detailedForecast": "A slight chance of rain and snow before 4pm. Mostly cloudy, with a high near 44."
        },
        {
          "number": 12,
          "name": "Thursday Night",
          "startTime": "2022-02-03T18:00:00-08:00",
          "endTime": "2022-02-04T06:00:00-08:00",
          "isDaytime": false,
          "temperature": 37,
          "temperatureUnit": "F",
          "temperatureTrend": null,
          "windSpeed": "3 mph",
          "windDirection": "SSE",
          "icon": "https://api.weather.gov/icons/land/night/bkn/rain?size=medium",
          "shortForecast": "Mostly Cloudy then Slight Chance Light Rain",
          "detailedForecast": "A slight chance of rain after 4am. Mostly cloudy, with a low around 37."
        },
        {
          "number": 13,
          "name": "Friday",
          "startTime": "2022-02-04T06:00:00-08:00",
          "endTime": "2022-02-04T18:00:00-08:00",
          "isDaytime": true,
          "temperature": 46,
          "temperatureUnit": "F",
          "temperatureTrend": null,
          "windSpeed": "6 mph",
          "windDirection": "SSE",
          "icon": "https://api.weather.gov/icons/land/day/rain?size=medium",
          "shortForecast": "Chance Light Rain",
          "detailedForecast": "A chance of rain. Mostly cloudy, with a high near 46."
        },
        {
          "number": 14,
          "name": "Friday Night",
          "startTime": "2022-02-04T18:00:00-08:00",
          "endTime": "2022-02-05T06:00:00-08:00",
          "isDaytime": false,
          "temperature": 39,
          "temperatureUnit": "F",
          "temperatureTrend": null,
          "windSpeed": "5 mph",
          "windDirection": "S",
          "icon": "https://api.weather.gov/icons/land/night/rain?size=medium",
          "shortForecast": "Slight Chance Light Rain",
          "detailedForecast": "A slight chance of rain before 4am. Mostly cloudy, with a low around 39."
        }
      ]
    }
  }
})
