baseURL = "https://blog.always-onward.com/"
title = "Onward Blog"
author = "Tom Woodard"
copyright = "Copyright © 2020"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
ignoreFiles = ['__.*']

# these options are overwridden on deployment
contentDir = "../../onward-blog/content"
publishDir  = "../../onward-blog/public"


theme = "blog"

[params]
  github = "https://github.com/SeriesOfUnlikelyExplanations/hugo-serverless"
  description = "Welcome to Adventure!"
  mainSections = ["posts"]

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "campsites"
    name = "Campsite Reviews"
    url = "/campsites/"
    weight = 20
  [[menu.main]]
    identifier = "sara-quote"
    name = "Sara's Quotes"
    url = "/sara-quotes/"
    weight = 40

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true
  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[caches]
  [caches.assets]
    dir = ':cacheDir/_gen'
    maxAge = -1
  [caches.getcsv]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.getjson]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.images]
    dir = ':cacheDir/_gen'
    maxAge = -1
  [caches.modules]
    dir = ':cacheDir/modules'
    maxAge = -1

[deploy]
region = 'us-west-2'
certificateArn = 'arn:aws:acm:us-east-1:718523126320:certificate/759a286c-c57f-44b4-a40f-4c864a8ab447'
hostedZoneId = 'Z0092175EW0ABPS51GQB'
siteName = 'blog.always-onward.com'
zoneName = 'always-onward.com'
