'use strict';

const data = {
  logged_out: {
    login: false,
    redirect_url: "https://auth.always-onward.com/login?client_id=clientId&response_type=code&scope=email+openid+phone+profile&redirect_uri=https://url/api/auth/callback"
  },
  logged_in: {
    "login":true,
    "redirect_url":"/api/auth/logout"
  },
  gallery_html: `<div id="carousel0" class="carousel" duration="100" items="1">
    <ul>
      <li id="c0_slide1" style="min-width: 100%; padding-bottom: 500px"><img src="ready1.jpg" alt=""></li>
      <li id="c0_slide2" style="min-width: 100%; padding-bottom: 500px"><img src="ready2.jpg" alt=""></li> 
    </ul>
    <ol>
      <li><a href="#c0_slide1"></a></li>
      <li><a href="#c0_slide2"></a></li>
    </ol>
    <div class="prev">‹</div>
    <div class="next">›</div>
  </div>`,
  weather: {"json":[{"number":1,"name":"This Afternoon","startTime":"2021-12-26T16:00:00-08:00","endTime":"2021-12-26T18:00:00-08:00","isDaytime":true,"temperature":30,"temperatureUnit":"F","temperatureTrend":"falling","windSpeed":"26 mph","windDirection":"NNW","icon":"https://api.weather.gov/icons/land/day/snow,30?size=medium","shortForecast":"Chance Light Snow","detailedForecast":"A chance of snow. Mostly cloudy. High near 30, with temperatures falling to around 25 in the afternoon. Wind chill values as low as 9. North northwest wind around 26 mph, with gusts as high as 35 mph. Chance of precipitation is 30%. New snow accumulation of less than half an inch possible."},
    {"number":2,"name":"Tonight","startTime":"2021-12-26T18:00:00-08:00","endTime":"2021-12-27T06:00:00-08:00","isDaytime":false,"temperature":19,"temperatureUnit":"F","temperatureTrend":"rising","windSpeed":"15 to 26 mph","windDirection":"NNW","icon":"https://api.weather.gov/icons/land/night/snow,20/wind_bkn?size=medium","shortForecast":"Slight Chance Light Snow then Mostly Cloudy","detailedForecast":"A slight chance of snow before 8pm. Mostly cloudy. Low around 19, with temperatures rising to around 22 overnight. Wind chill values as low as 8. North northwest wind 15 to 26 mph, with gusts as high as 35 mph. Chance of precipitation is 20%. New snow accumulation of less than half an inch possible."},
    {"number":3,"name":"Monday","startTime":"2021-12-27T06:00:00-08:00","endTime":"2021-12-27T18:00:00-08:00","isDaytime":true,"temperature":25,"temperatureUnit":"F","temperatureTrend":null,"windSpeed":"5 to 15 mph","windDirection":"NE","icon":"https://api.weather.gov/icons/land/day/bkn?size=medium","shortForecast":"Partly Sunny","detailedForecast":"Partly sunny, with a high near 25. Wind chill values as low as 8. Northeast wind 5 to 15 mph."},
    {"number":4,"name":"Monday Night","startTime":"2021-12-27T18:00:00-08:00","endTime":"2021-12-28T06:00:00-08:00","isDaytime":false,"temperature":22,"temperatureUnit":"F","temperatureTrend":null,"windSpeed":"7 mph","windDirection":"ESE","icon":"https://api.weather.gov/icons/land/night/snow,20/bkn?size=medium","shortForecast":"Slight Chance Light Snow then Mostly Cloudy","detailedForecast":"A slight chance of snow between 7pm and 10pm. Mostly cloudy, with a low around 22. Wind chill values as low as 16. East southeast wind around 7 mph. Chance of precipitation is 20%."},
    {"number":5,"name":"Tuesday","startTime":"2021-12-28T06:00:00-08:00","endTime":"2021-12-28T18:00:00-08:00","isDaytime":true,"temperature":31,"temperatureUnit":"F","temperatureTrend":null,"windSpeed":"6 mph","windDirection":"NNE","icon":"https://api.weather.gov/icons/land/day/bkn/snow,20?size=medium","shortForecast":"Partly Sunny then Slight Chance Light Snow","detailedForecast":"A slight chance of snow after 4pm. Partly sunny, with a high near 31. North northeast wind around 6 mph. Chance of precipitation is 20%."},
    {"number":6,"name":"Tuesday Night","startTime":"2021-12-28T18:00:00-08:00","endTime":"2021-12-29T06:00:00-08:00","isDaytime":false,"temperature":22,"temperatureUnit":"F","temperatureTrend":null,"windSpeed":"7 mph","windDirection":"N","icon":"https://api.weather.gov/icons/land/night/snow,20/bkn?size=medium","shortForecast":"Slight Chance Light Snow then Mostly Cloudy","detailedForecast":"A slight chance of snow before 10pm. Mostly cloudy, with a low around 22. Chance of precipitation is 20%."},
    {"number":7,"name":"Wednesday","startTime":"2021-12-29T06:00:00-08:00","endTime":"2021-12-29T18:00:00-08:00","isDaytime":true,"temperature":31,"temperatureUnit":"F","temperatureTrend":null,"windSpeed":"3 to 7 mph","windDirection":"NNE","icon":"https://api.weather.gov/icons/land/day/sct/snow,20?size=medium","shortForecast":"Mostly Sunny then Slight Chance Light Snow","detailedForecast":"A slight chance of snow after 4pm. Mostly sunny, with a high near 31. Chance of precipitation is 20%."},
    {"number":8,"name":"Wednesday Night","startTime":"2021-12-29T18:00:00-08:00","endTime":"2021-12-30T06:00:00-08:00","isDaytime":false,"temperature":25,"temperatureUnit":"F","temperatureTrend":null,"windSpeed":"3 to 9 mph","windDirection":"SSE","icon":"https://api.weather.gov/icons/land/night/snow?size=medium","shortForecast":"Light Snow","detailedForecast":"Snow. Mostly cloudy, with a low around 25. New snow accumulation of less than one inch possible."},
    {"number":9,"name":"Thursday","startTime":"2021-12-30T06:00:00-08:00","endTime":"2021-12-30T18:00:00-08:00","isDaytime":true,"temperature":38,"temperatureUnit":"F","temperatureTrend":null,"windSpeed":"6 to 10 mph","windDirection":"SSW","icon":"https://api.weather.gov/icons/land/day/snow?size=medium","shortForecast":"Light Snow","detailedForecast":"Snow before 10am, then rain and snow. Mostly cloudy, with a high near 38. New snow accumulation of around one inch possible."},
    {"number":10,"name":"Thursday Night","startTime":"2021-12-30T18:00:00-08:00","endTime":"2021-12-31T06:00:00-08:00","isDaytime":false,"temperature":30,"temperatureUnit":"F","temperatureTrend":null,"windSpeed":"6 mph","windDirection":"W","icon":"https://api.weather.gov/icons/land/night/snow?size=medium","shortForecast":"Rain And Snow Likely","detailedForecast":"Rain and snow likely. Mostly cloudy, with a low around 30. New snow accumulation of around one inch possible."},
    {"number":11,"name":"Friday","startTime":"2021-12-31T06:00:00-08:00","endTime":"2021-12-31T18:00:00-08:00","isDaytime":true,"temperature":36,"temperatureUnit":"F","temperatureTrend":null,"windSpeed":"7 mph","windDirection":"N","icon":"https://api.weather.gov/icons/land/day/snow?size=medium","shortForecast":"Slight Chance Rain And Snow","detailedForecast":"A slight chance of rain and snow. Partly sunny, with a high near 36. Little or no snow accumulation expected."},
    {"number":12,"name":"Friday Night","startTime":"2021-12-31T18:00:00-08:00","endTime":"2022-01-01T06:00:00-08:00","isDaytime":false,"temperature":26,"temperatureUnit":"F","temperatureTrend":null,"windSpeed":"6 mph","windDirection":"E","icon":"https://api.weather.gov/icons/land/night/snow?size=medium","shortForecast":"Chance Light Snow","detailedForecast":"A chance of snow. Mostly cloudy, with a low around 26."},
    {"number":13,"name":"New Year's Day","startTime":"2022-01-01T06:00:00-08:00","endTime":"2022-01-01T18:00:00-08:00","isDaytime":true,"temperature":39,"temperatureUnit":"F","temperatureTrend":null,"windSpeed":"6 to 10 mph","windDirection":"SSE","icon":"https://api.weather.gov/icons/land/day/snow?size=medium","shortForecast":"Chance Light Snow then Rain And Snow","detailedForecast":"A chance of snow before 7am, then rain and snow. Mostly cloudy, with a high near 39."},
    {"number":14,"name":"Saturday Night","startTime":"2022-01-01T18:00:00-08:00","endTime":"2022-01-02T06:00:00-08:00","isDaytime":false,"temperature":36,"temperatureUnit":"F","temperatureTrend":null,"windSpeed":"12 mph","windDirection":"S","icon":"https://api.weather.gov/icons/land/night/rain?size=medium","shortForecast":"Light Rain","detailedForecast":"Rain. Cloudy, with a low around 36."}],
    "html":"<div class=\"forecast-wrapper\">\n        <div class=\"forecast-day\">    \n      <div class=\"forecast-section forecast-section--day\">\n        <strong class=\"forecast-section__name\">This Afternoon</strong>\n        <img class=\"forecast-section__icon\" src=\"https://api.weather.gov/icons/land/day/snow,30?size=medium\" alt=\"Chance Light Snow\">\n        <div class=\"forecast-section__temp\">30&deg; F</div>\n        <div class=\"forecast-section__short\">Chance Light Snow</div>\n        <div class=\"forecast-section__wind\">Wind: 26 mph NNW</div>\n      </div>\n      <div class=\"forecast-section forecast-section--night\">\n      <strong class=\"forecast-section__name\">Tonight</strong>\n      <img class=\"forecast-section__icon\" src=\"https://api.weather.gov/icons/land/night/snow,20/wind_bkn?size=medium\" alt=\"Slight Chance Light Snow then Mostly Cloudy\">\n      <div class=\"forecast-section__temp\">19&deg; F</div>\n      <div class=\"forecast-section__short\">Slight Chance Light Snow then Mostly Cloudy</div>\n      <div class=\"forecast-section__wind\">Wind: 15 to 26 mph NNW</div>\n    </div>\n    </div>\n      </div>\n      <p class=\"forecast-credits\">Forecast provided by the <a href=\"https://www.weather.gov/\">National Weather Service</a>.</p>"}
}

export default data; 
