name: Deploy
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - live
jobs:
 build:
    name: Build and deploy
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Configure NPM
        run: |
          npm install
          cd functions/adminLambda
          npm install --production
          cd ../apiLambda
          npm install --production
          cd ../siteGeneratorLambda
          npm install --production
          
      - name: Run unit tests
        run: |
          npm run test-generator-deploy
          npm run test-admin-deploy
          npm run test-api-deploy
          npm run test-frontend-deploy
        env:
          AWS_ACCESS_KEY_ID: 'testKey'
          AWS_SECRET_ACCESS_KEY: 'testSecret'
      
      - name: Test CDK
        run: |
          npm run test-cdk
        env:
          AWS_ACCESS_KEY_ID: 'testKey'
          AWS_SECRET_ACCESS_KEY: 'testSecret'
      
      - name: Deploy
        run: |
          npm run deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - uses: codecov/codecov-action@v1
        name: upload generator coverage
        with:
          file: functions/siteGeneratorLambda/coverage/*.json
          flags: siteGeneratorLambda
          fail_ci_if_error: true
          
      - uses: codecov/codecov-action@v1
        name: upload adminLambda coverage
        with:
          file: functions/adminLambda/coverage/*.json
          flags: adminLambda
          fail_ci_if_error: true

      - uses: codecov/codecov-action@v1
        name: upload apiLambda coverage
        with:
          file: functions/apiLambda/coverage/*.json
          flags: apiLambda
          fail_ci_if_error: true

      - uses: codecov/codecov-action@v1
        name: upload frontEnd coverage
        with:
          file: hugo-serverless-theme/coverage/*.json
          flags: frontEnd
          fail_ci_if_error: true

