name: Deploy
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - live
jobs:
 build:
    name: Build and deploy
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Configure NPM
        run: |
          npm install
          cd functions/adminLambda
          npm install --production
          cd ../functions/siteGeneratorLambda
          pip install pipenv
          pipenv install
          cp -r $(pipenv --venv)/lib/python3.8/site-packages/. .
          
      - name: Deploy
        run: |
          npm run deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
